version: '3.8'

services:
  jwt_service:
    build:
      context: ./services/jwt_service
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TOKEN_EXPIRATION=30
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS="--requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    # command: redis-server --appendonly yes
    restart: unless-stopped

  url_shortener:
    build:
      context: ./services/url_shortener_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/url_shortener_service:/app  # Ensure correct volume mapping
    environment:
      - FLASK_ENV=development
    restart: always
    
volumes:
  redis_data:
    driver: local