apiVersion: v1
kind: Service
metadata: 
  name: jwt
  namespace: url-shortener
spec:
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: jwt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt
  template:
    metadata:
      labels:
        app: jwt
    spec:
      containers:
        - name: jwt
          image: zero3river/wc-ass:jwt
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-pass
                  key: REDIS_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT

            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_DB
            
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET_KEY

...
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jwt-hpa
  namespace: url-shortener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jwt
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60