apiVersion: v1
kind: Service
metadata: 
  name: url
  namespace: url-shortener
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url
  template:
    metadata:
      labels:
        app: url
    spec:
      containers:
        - name: url
          image: docker.io/library/wc-ass-url:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-pass
                  key: REDIS_PASSWORD

            - name: REDIS_HOST
              valueFrom:
                configMapRef:
                  name: app-config
                  key: REDIS_HOST

            - name: REDIS_PORT
              valueFrom:
                configMapRef:
                  name: app-config
                  key: REDIS_PORT

            - name: REDIS_DB
              valueFrom:
                configMapRef:
                  name: app-config
                  key: REDIS_DB

            - name: JWT_SERVER
              valueFrom:
                configMapRef:
                  name: app-config
                  key: JWT_SERVER

...
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: url-hpa
  namespace: url-shortener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60