apiVersion: v1
kind: Service
metadata:
  name: user-management
  namespace: url-shortener
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: user-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: docker.io/library/wc-ass-user_management:latest
          # TODO: I'm not sure if the image is correct?
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          # envFrom:
          #   - secretRef:
          #       name: app-secrets
          # TODO Switch to the configmap and secrets
          env:
            - name: MYSQL_HOST
              value: "mysql-cluster"
            - name: MYSQL_PORT
              value: "3306"
            - name: JWT_SERVER
              value: "http://jwt-service:8002/auth"
            - name: MYSQL_USER 
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: sakila
            - name: MYSQL_PASSWORD
              value: sakila
            - name: MYSQL_DB
              value: users

...
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-management-hpa
  namespace: url-shortener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-management
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60