apiVersion: v1
kind: Service
metadata:
  name: user-management
  namespace: url-shortener
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: user-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: zero3river/wc-ass:user_management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          # envFrom:
          #   - secretRef:
          #       name: app-secrets
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_PORT
            - name: JWT_SERVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_SERVER
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: rootUser
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: rootPassword
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_MYSQL_DB

...
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-management-hpa
  namespace: url-shortener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-management
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60